### ISSUE TITLE
QRCode - No way to dismiss 

### ISSUE THREAD

**Issue by psysoo** [GuideBlocks-org/iOS-GuideBlocks#62] opened 2024-02-29 23:40 UTC
QRCode - User can't dismiss the guide by touch out or dismiss button (not available even if it's set on dash)

<img width="406" alt="Screenshot 2024-03-01 at 10 39 14 am" src="https://github.com/GuideBlocks-org/iOS-GuideBlocks/assets/114545794/03bcddd8-6a62-409e-a7af-7675dae7576f">

**Comment by amraboelela** [comment] 2024-03-02 04:03
Couldn't reproduce this issue, pls check again after merging #66

**Comment by amraboelela** [comment] 2024-03-02 04:05
Dashboard sync is currently down, but this is what i see in the xCode Canvas:

<img width="335" alt="Screenshot 2024-03-01 at 8 04 44 PM" src="https://github.com/GuideBlocks-org/iOS-GuideBlocks/assets/882954/9a6b3206-ebde-407a-9454-a2e7b9977e2d">

**Comment by amraboelela** [comment] 2024-03-02 19:34
Now the syncing is working and it looks ok with me
<img width="778" alt="Screenshot 2024-03-02 at 11 34 03 AM" src="https://github.com/GuideBlocks-org/iOS-GuideBlocks/assets/882954/f223ed45-c11f-4e99-9acc-0129a1b8efb1">

**Comment by djinoz** [comment] 2024-03-03 04:24
Merged

**Comment by psysoo** [comment] 2024-03-04 05:01
Hi @amraboelela 
this is what I can see (same container size 70%) and touch out (touch outside of the guide) doesn't work. 
<img width="1445" alt="Screenshot 2024-03-04 at 3 59 10 pm" src="https://github.com/GuideBlocks-org/iOS-GuideBlocks/assets/114545794/7053afb2-815a-407b-bd93-372bae7228bb">

Touch out setting is here
<img width="1432" alt="Screenshot 2024-03-04 at 4 01 04 pm" src="https://github.com/GuideBlocks-org/iOS-GuideBlocks/assets/114545794/4fe6a825-8c1a-4fd1-a289-b50d6b396ef2">

**Comment by amraboelela** [comment] 2024-03-05 01:35
Try again after merging #72

**Comment by psysoo** [comment] 2024-03-06 05:56
@mdstroebel  I can't see this change in the latest build of https://repo.contextu.al/ui/native/contextual/ios/bdd/dev_prod/swift_airbnb_dj/  
Although the lasted build contains @amraboelela 's fix https://github.com/GuideBlocks-org/iOS-GuideBlocks/issues/50 

<img width="1474" alt="Screenshot 2024-03-06 at 4 53 34 pm" src="https://github.com/GuideBlocks-org/iOS-GuideBlocks/assets/114545794/957424e3-ddb6-4d15-add8-45a039d6cfc2">
<img width="1492" alt="Screenshot 2024-03-06 at 4 53 50 pm" src="https://github.com/GuideBlocks-org/iOS-GuideBlocks/assets/114545794/77f3d425-81b1-4bbd-8b92-ffdee908ad5d">

**Comment by psysoo** [comment] 2024-03-11 05:39
Hi @amraboelela 

I tested it on [509ff81](https://github.com/GuideBlocks-org/iOS-GuideBlocks/commit/509ff81ff4af50b34e2fddb2af6a7028a4b9594b) 
Now the guide can be dismissed by touch-out event.
However, can't be dismissed by X dismiss button
please refer to below recording
https://github.com/GuideBlocks-org/iOS-GuideBlocks/assets/114545794/70255a8b-007f-48a6-8830-bed5290f7918

**Comment by psysoo** [comment] 2024-03-21 05:48
test passed with dev sdk 3.0.3 
QRCode guide can be dismissed by touch-out and X dismiss button

**Closed** 2024-03-21 05:49 UTC
Labels: bug
